Tests
Oluwadamilareolusakin/testing-with-jest pull request #1
Opened 2019-12-06 20:54 UTC by Oluwadamilareolusakin

# Description
This PR contains the following functions as well as tests for them using JEST:

#### Caesar's Cypher
Caesar's cypher is a cryptographic cypher you can read all about [here](http://practicalcryptography.com/ciphers/caesar-cipher/)
Tests were written for the following edge cases:
* Shifts letters the appropriate number of times forward depending on the key given.
* Wraps around from z-a
* Maintains initial character case

#### Calculator (with addition, subtraction, division and multiplication functions)
Tests were written for the following edge cases: 
* Addition adds two numbers correctly
* Subtraction subtracts one number from another
* Multiplication gives the product of two numbers
* Division gives the result of one number divided by another

#### Analyze array
This function takes an array and returns the following details about the array: 
* Length
* Max(largest number)
* Min(smallest number)
* Average

##### Tests were written to ascertain that the right values where returned.

#### Capitalize
A function that capitalizes a string
##### Tests were written to ensure the correct values are returned.

#### Reverse
A funtion that reverses a string
##### Tests were written to ensure correct revearsal

2019-12-07 03:03 UTC, Oghenebrume50 requested changes
STATUS: Changes Required

Hi @Oluwadamilareolusakin good job on this one man, :clap: you just make some few changes and we are good
The caeser chipher seems to change everything, this is not the desired behaviour you want to change only the alphabets and take note of punctuations they do not change
![see the requirement](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/testing_practice/caesar_requirement.png)
Please make changes and request a re-review 

Raphael Noriode

2019-12-07 03:03 UTC, Oghenebrume50 commented on functions/analyse.js
> +}
analyze should be an object that has function properties like min and max, so that it can be accessed like this analyze.min

2019-12-07 09:32 UTC, Oluwadamilareolusakin commented on functions/analyse.js
> +}
Hey man, thanks for the review. Based on the description of the analyze function, it is meant to return an object that contains that properties of the array passed in as an argument which is what I've done :rocket:.

2019-12-07 09:34 UTC, Oluwadamilareolusakin commented
# Changes made as requested :smile: 
* I have corrected the issue with the punctuations
* The issue with the analyze function isn't really an issue, it works as described in the Odin Project Assignment

2019-12-07 14:40 UTC, bellom requested changes
## Hi @Oluwadamilareolusakin  :clap: 

**Great work making some necessary corrections from the previous review.**

**For some reason i ran into one failing test, screenshot below;**
![image](https://user-images.githubusercontent.com/31897434/70376282-92685d00-1907-11ea-87c4-e2a01f572cf1.png)


**Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....**

Best,

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2019-12-07 15:44 UTC, Oluwadamilareolusakin commented
@bellom a bit of oversight, I changed the way the program runs but forgot to uplate the tests. It's failing bexcuse punctuations are no longer encrypted. Will correct as requested.

2019-12-09 18:44 UTC, azdrenymeri commented
### Tests are passing 👍 
#### You can merge

2019-12-12 22:13 UTC, merged